# --- 경로 설정 ---
dataPath: ../ComfyU-auto-script_data  # 설정파일 폴더. 변경시 재실행 필요.
base_dir: W:\ComfyUI_windows_portable  # 작업 디렉토리

# --- 처리할 타입 리스트 ---
types:
  - IL
  - Pony

# --- 제거할 태그 목록 ---
# 정규식 패턴 사용 가능: "/pattern/" 형태로 감싸면 정규식으로 인식됩니다.
# 예: '/^background.*$/' (background로 시작하는 모든 태그)
# 예: '/.*weapon.*/' (weapon을 포함하는 모든 태그)
excluded_tags:
  - '/cum .*/'
  - '/from .*/'
  - '/holding .*/'
  - '/.* body/'
  - '/.* penis/'
  - '/.* armor/'
  - '/.* cum/'
  - '/.* mouth/'
  - '/.* background/'
  - 'looking at viewer'
  - 'censored'
  - 'weapon'
  - 'blush'
  - 'doggystyle'
  - 'sword'
  - 'kneeling'
  - 'clothed female nude male'
  - 'blurry'
  - 'armor'
  - 'anime coloring'
  - 'hand up'
  - 'indoors'
  - 'standing'
  - '1boy'
  - 'ass'
  - 'nipples'
  - 'hetero'
  - 'cum'
  - 'ahoge'
  - 'sitting'
  - 'one eye closed'
  - 'breasts out'
  - 'large breasts'
  - 'mole'
  - 'mosaic censoring'
  - 'smile'
  - 'vaginal'
  - 'penis'
  - 'pussy'
  - 'tongue'
  - 'sex'
  - 'solo'
  - 'tongue out'
  - 'pov'
  - 'solo focus'
  - 'nude'
  - 'arm grab'
