# --- 경로 설정 ---
dataPath: ../ComfyU-auto-script_data  # 설정파일 폴더. 변경시 재실행 필요.
base_dir: W:\ComfyUI_windows_portable  # 작업 디렉토리

# --- 처리할 타입 리스트 ---
types:
  - IL
  - Pony

# --- 제거할 태그 목록 ---
# 정규식 패턴 사용 가능: "/pattern/" 형태로 감싸면 정규식으로 인식됩니다.
# 예: '/^background.*$/' (background로 시작하는 모든 태그)
# 예: '/.*weapon.*/' (weapon을 포함하는 모든 태그)
excluded_tags:
  - '/cum .*/'
  - '/from .*/'
  - '/mole .*/'
  - '/holding .*/'
  - '/.* body/'
  - '/.* penis/'
  - '/.* armor/'
  - '/.* horns/'
  - '/.* cum/'
  - '/.* mouth/'
  - '/.* background/'
  - 'looking at viewer'
  - 'censored'
  - 'weapon'
  - 'horns'
  - 'holding'
  - 'blush'
  - 'doggystyle'
  - 'sword'
  - 'kneeling'
  - 'clothed female nude male'
  - 'blurry'
  - 'armor'
  - 'anime coloring'
  - 'hand up'
  - 'indoors'
  - 'standing'
  - '1boy'
  - 'ass'
  - 'nipples'
  - 'outdoors'
  - 'hetero'
  - 'cum'
  - 'ahoge'
  - 'sitting'
  - 'one eye closed'
  - 'breasts out'
  - 'large breasts'
  - 'mole'
  - 'mosaic censoring'
  - 'smile'
  - 'vaginal'
  - 'penis'
  - 'pussy'
  - 'tongue'
  - 'sex'
  - 'solo'
  - 'tongue out'
  - 'pov'
  - 'solo focus'
  - 'nude'
  - 'arm grab'

# --- dress 필드로 이동할 태그 목록 ---
# 이 태그들은 char 필드에서 제거되고 dress 필드에 '{  태그들 |4::__dress__},' 형태로 추가됩니다.
# 정규식 패턴 사용 가능: "/pattern/" 형태로 감싸면 정규식으로 인식됩니다.
dress_tags:
  - 'top'
  - '/.*sleeves.*/'
  - '/.*jewelry.*/'
  - '/.*thighhighs.*/'
  - '/.* top.*/'
  - '/.* hat.*/'
  - '/.* socks.*/'
  - '/.* cap.*/'
  - '/.*underwear.*/'
  - '/.*nurse.*/'
  - '/.*footwear.*/'
  - '/.*gloves.*/'
  - '/.*boot.*/'
  - '/.*thigh.*/'
  - '/.*dress.*/'
  - '/.*skirt.*/'
  - '/.*shoulders.*/'
  - '/.*piercing.*/'
  - '/.*shirt.*/'
  - '/.*uniform.*/'
  - '/.*clothing.*/'
  - '/.*outfit.*/'
  - '/.*panties.*/'
  - '/.* cleavage.*/'
  - '/.* jacket.*/'
